---
title: "Tarea final"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
---


```{r setup, include=FALSE}
library(flexdashboard) # always
```

<!-- links -->
```{r}
map1link='https://github.com/datoesp2026/Tarea-final/raw/main/map_rook.rds'
viz1=url(map1link)

map2link='https://github.com/datoesp2026/Tarea-final/raw/main/map_knn.rds'
viz2=url(map2link)

map3link='https://github.com/datoesp2026/Tarea-final/raw/main/map_band.rds'
viz3=url(map3link)

map4link='https://github.com/datoesp2026/Tarea-final/raw/main/map_kernel.rds'
viz4=url(map4link)
```

## Intro {.sidebar}

Se observa 4 mapas distritales del departamento de Lima, mostrando su relación entre distritos con respecto a la variable de educación. 


## Column {data-width="450"}

### Método Contigüidad (Queen) 

```{r}

readRDS(viz1)
```

### Método K-vecinos fijos (binario)

```{r}

readRDS(viz2)
```

## Column {data-width="550"}

### Método Banda de distancia (binario)

```{r}
readRDS(viz3)
```

### Método K-vecinos con peso continuo

```{r}
readRDS(viz4)
```
